### ISSUE TITLE
Increase precision for average latency output

### ISSUE THREAD

**Issue by Bvangoor** [filebench/filebench#100]
We are trying to find out the latency of the request during the experiment from the file bench results, and following is  a sample filebench output:

Bharaths-MBP:fuse-fast2017 Bharath$ 
11.443: IO Summary: 279868 ops 27982.608 ops/s 0/27983 rd/wr 109.3mb/s   0.0ms/op
21.445: Per-Operation Breakdown
finish               0ops        0ops/s   0.0mb/s      0.0ms/op [0.00ms -  0.00ms]
close1               0ops        0ops/s   0.0mb/s      0.0ms/op [0.00ms -  0.00ms]
write-file           280325ops    28028ops/s 109.5mb/s      **0.0ms/op** [0.02ms - 528.24ms]
create1              0ops        0ops/s   0.0mb/s      0.0ms/op [0.00ms -  0.00ms]
21.445: IO Summary: 280325 ops 28028.055 ops/s 0/28028 rd/wr 109.5mb/s   0.0ms/op

Since the result (in bold) is rounded to one digit (after comma) there should be more precision.

**Comment by gamvrosi** [comment]
This is a good point, we should switch to microsecond precision. @sectorsize512 aren't we currently using `gettimeofday()`? We should probably switch to something that is guaranteed to be monotonic and provide at least microsecond precision, e.g. `clock_gettime()`, in newer systems.

**Comment by sectorsize512** [comment]
@gamvrosi, I think @Bvangoor refers to the printing format. We'rounding the latency to a single digit after comma with printf. This should be very to fix.

As of using clock_gettime() - how generic it is? Doesn't gettimeofday() use cloc_gettime() internally on modern systems? I generally would like to understand what are the time sources available in Linux and their differences. Do you have any info on that?

**Comment by sectorsize512** [comment]
@Bvangoor, will you or the students you work with make a pull request for this fix?

**Comment by swamintn** [comment]
I'll work on fixing this...

**Comment by Bvangoor** [comment]
Thanks Swami.

Vasily,
Regarding your question on available time sources in linux: During our project on finding latencies between user space and kernel components I found these functions:
In Userspace : clock_gettime(CLOCK_MONOTONIC, &tms)
In Kernel : do_posix_clock_monotonic_gettime(&tms)
are in sync and gives you monotonic time in the order of nano secs.

If you change "CLOCK_MONOTONIC" to "CLOCK_REALTIME" you get the CPU time (but I supoose you do not need this for this use case).

**Comment by sectorsize512** [comment]
Fixed with pull request #101.
