### ISSUE TITLE
syntax error at 'sudo' around line 3

### ISSUE THREAD

**Issue by Sitora21** [filebench/filebench#104]
I am trying to run the following code:

`sudo filebench << SCRIPT >> seqReadResultsfb.txt
load filemicro_seqread
run 720
SCRIPT
echo "Starting test" $(date +"%H:%M:%S") >> seqReadfb.txt`

However it throw this error:

`0.000: Allocated 173MB of shared memory
 0.008: syntax error at 'sudo' around line 3
 Warning: no run command in the WML script!`

Any advice what is going wrong ?

**Comment by sectorsize512** [comment]
Hi, you need to run Filebench like this:

filebench -f <workload.f>

If you still have an issue, paste the contents of workload.f file here and we can help you further.

**Comment by Sitora21** [comment]
Thank you for your response.
to run the Filebench I used  filebench -f sqReadfb.f

In the sqReadfb.f  file is the following code.

'#! /bin/bash'
 
'sudo filebench << SCRIPT >> seqReadResultsfb.txt'
'load' 
'run 720'
'SCRIPT'
 
'echo "Starting test" $(date +"%H:%M:%S") >> seqReadfb.txt'
'echo $(grep 'Summary' seqReadResultsfb.txt) >> seqReadfb.txt'
'echo "Ending test" $(date +"%H:%M:%S") >> seqReadfb.txt'
 
'rm seqReadResultsfb.txt'


I still keep getting the same error though. 

'0.000: Allocated 173MB of shared memory 0.008: '
'syntax error at 'sudo' around line 3' 
'Warning: no run command in the WML script'

**Comment by sectorsize512** [comment]
Hi,

Currently, you workload file does not define any workload. I.e., no processes, no threads, no flowops. There is no 'load' command in Filebench's WML language. (The command previously existed n the wrapper for Filebench).

I suggested you to read the following:

https://github.com/filebench/filebench/wiki

As a quick start guide on writing WML files.

**Comment by sectorsize512** [comment]
Closing as it seems the question got answered.
