### ISSUE TITLE
custom variable fails

### ISSUE THREAD

**Issue by snalli** [filebench/filebench#109]
$ ./filebench -f workloads/webserver.f
0.000 : Failed to open cvar-directory around line 1
0.000 : Undefined custom variable cvar-gamma around line 29
define cvar : failed for custom variable $filesize

Custom variables seems like a really bad idea with all these runtime
and sometimes compilation issues.

**Comment by sectorsize512** [comment]
Did you run make install to install custom variable?

**Comment by yyniupi2333** [comment]
I need to port the static cross compiled executable file to the embedded platform, so I did not use "make install" for installation. There is a problem with not being able to open the cvar directory on the embedded platform. Is there any solution？
