### ISSUE TITLE
Cannot run the netsfs.f workload

### ISSUE THREAD

**Issue by fdsscz** [filebench/filebench#111]
Recently I tried the Network File Server (netsfs.f). And it reported the following error.

Filebench Version 1.5-alpha3
0.000: Allocated 173MB of shared memory
0.001: syntax error at 'randvar' around line 39
Warning: no run command in the WML script!

Can anyone take a loot at this?

Thanks in advance.

Zhen

**Comment by sectorsize512** [comment]
Zhen,

I might have fixed the issue in this repo/branch:

https://github.com/sectorsize512/filebench/tree/issue111fix

Could you try?

Thanks,
Vasily

**Comment by sectorsize512** [comment]
Fixed with:

f67e046dcd1c9a5844b70d8f3e1e8d88217e9237
ca734319b834c316b74321f4420fda270dd280a4
