### ISSUE TITLE
How to get the read, write system calls issued by Filebench

### ISSUE THREAD

**Issue by sarthak-chakraborty** [filebench/filebench#162]
Hi, 

I am new the Filebench, and I would want a list of system calls (`read()`, `write()`, `open()` etc.) that filebench issues to test our FS. 

I have been trying to do it by using `strace`. For this, I would need a PID for the process. If I do `ps aux | grep filebench`, multiple processes are shown:
```
geniuser    5989  0.0  0.0   8480  5728 ?        S    Oct30   0:00 /usr/libexec/emulab/program-agent -e dcsq-PG0/filebench -s localhost -l /var/emulab/logs/progagent.debug -v node0 -t /var/tmp/progagent-token.5988 -d -i /var/run/progagent.pid -k /var/emulab/boot/eventkey -c /var/emulab/boot/progagents
root        6037  0.0  0.0   8176  3972 ?        Ss   Oct30   0:00 linktest -e dcsq-PG0/filebench -s localhost -l /var/emulab/logs/linktest.debug -i /var/run/linktest.pid -k /var/emulab/boot/eventkey -u geniuser
root       54914  0.0  0.0  11492  5688 pts/0    S+   18:00   0:00 sudo filebench -f test.f
root       54915  0.0  0.0  11492   888 pts/2    Ss   18:00   0:00 sudo filebench -f test.f
root       54916  1.2  0.0 203480 45820 pts/2    Sl+  18:00   0:00 filebench -f test.f
root       54921 83.2  0.0 258716  3048 pts/2    Sl+  18:00   0:03 readerP -a readerP -i 1 -s 0x7fffecc3b000 -m /tmp/filebench-shm-AYGwXU
```

For each of these, I have tried to pin the process to strace, but none of them gave the system calls that I want. The system calls that strace gives are `ppoll`, `pselect`, `clock_nanosleep`, etc.

How do I get the correct system calls?

**Comment by melody97** [comment]
Hi, 
you can add the tracepoints (e.g., printf function) in the fb_localfs.c, which contains the actual system calls about file system.
Then, recompile the filebench and run. It's better to redirect your stdout to one file.

**Comment by sarthak-chakraborty** [comment]
Thank you. It worked
