### ISSUE TITLE
Only one last defined process spans

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#26]
Only one last defined process spans even if there are multiple processes defined in .f file. When running attached file, that's what one sees:

root@white:/edisk-ext3/projects/dedup/in\_cvs/go\_filebench/go\_filebench-1.4.8/workloads\# go\_filebench -f /tmp/singlestreamread.f 
Filebench Version 1.4.8.fsl.0.9
4533: 0.000: Allocated 170MB of shared memory
4533: 0.001: Single Stream Read Version 2.0 personality successfully loaded
4533: 0.001: Creating/pre-allocating files and filesets
4533: 0.001: File largefile1: 5120.000MB
4533: 0.003: Removed any existing file largefile1 in 1 seconds
4533: 0.003: making tree for filset /tmp/largefile1
4533: 0.003: Creating file largefile1...
^C 4533: 5.047: Aborting...
root@white:/edisk-ext3/projects/dedup/in\_cvs/go\_filebench/go\_filebench-1.4.8/workloads\# vim /tmp/singlestreamread.f 
root@white:/edisk-ext3/projects/dedup/in\_cvs/go\_filebench/go\_filebench-1.4.8/workloads\# 
root@white:/edisk-ext3/projects/dedup/in\_cvs/go\_filebench/go\_filebench-1.4.8/workloads\# go\_filebench -f /tmp/singlestreamread.f 
Filebench Version 1.4.8.fsl.0.9
4538: 0.000: Allocated 170MB of shared memory
4538: 0.001: Single Stream Read Version 2.0 personality successfully loaded
4538: 0.001: Creating/pre-allocating files and filesets
4538: 0.001: File largefile1: 1024.000MB
4538: 0.001: Re-using file largefile1.
4538: 0.001: Creating file largefile1...
4538: 0.213: Preallocated 1 of 1 of file largefile1 in 1 seconds
4538: 0.213: waiting for fileset pre-allocation to finish
4540: 0.213: Starting 1 anotherseqread instances
4541: 0.214: Starting 1 anotherseqread threads
4538: 1.214: Running...
4538: 61.225: Run took 60 seconds...
4538: 61.226: Per-Operation Breakdown
limit                0ops        0ops/s   0.0mb/s      0.0ms/op        0us/op-cpu \[0ms - 0ms\]
anotherseqread       210923ops     3515ops/s 3511.4mb/s      0.2ms/op      260us/op-cpu \[0ms - 0ms\]
limit                0ops        0ops/s   0.0mb/s      0.0ms/op        0us/op-cpu \[18446744073709ms - 0ms\]
seqread              0ops        0ops/s   0.0mb/s      0.0ms/op        0us/op-cpu \[18446744073709ms - 0ms\]
4538: 61.226: IO Summary: 210923 ops, 3514.829 ops/s, \(3515/0 r/w\), 3511.4mb/s,    308us cpu/op,   0.2ms latency
4538: 61.226: Shutting down processes

Only anotherseqread processe is started\!

Reported by: vass-vass

**Comment by sectorsize512** [comment]
Fixed with 05d1187
