### ISSUE TITLE
Usage " (whatever)" causes parser's error

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#31]
if you add

usage " \(qkreq\)"

to the .f file, that's what you'll see

vass@Spear:~/filebenchqa/auto-test/filebench-1.4.9$ filebench 
Filebench Version 1.4.9
IMPORTANT: Virtual address space randomization is enabled on this machine\!
It is highly recommended to disable randomization to provide stable Filebench runs.
Echo 0 to /proc/sys/kernel/randomize\_va\_space file to disable the randomization.
WARNING: Could not open /proc/sys/kernel/shmmax file\!
It means that you probably ran Filebench not as a root. Filebench will not increase shared
region limits in this case, which can lead to the failures on certain workloads.
5034: 0.000: Allocated 126MB of shared memory
filebench&gt; load varmail
5034: 2.479: Varmail Version 3.0 personality successfully loaded
5034: 2.479: Usage: set $dir=&lt;dir&gt;
5034: 2.479:        set $meanfilesize=&lt;size&gt;    defaults to 16384
5034: 2.479:        set $nfiles=&lt;value&gt;     defaults to 1000
5034: 2.479:        set $nthreads=&lt;value&gt;   defaults to 16
5034: 2.479:        set $meanappendsize=&lt;value&gt; defaults to 16384
5034: 2.479:        set $iosize=&lt;size&gt;  defaults to 1048576
5034: 2.479:        set $meandirwidth=&lt;size&gt; defaults to 1000000
5034: 2.479:        run runtime \(e.g. run 60\)
5034: 2.479: \(directory depth defaults to 1 as in postmark
5034: 2.479: set $meandirwidth lower to increase depth beyond 1 if desired\)
5034: 2.479: Cannot find environment variable \(qkreq\) on line 69
5034: 2.479:  \(qkreq\)
filebench&gt; quit
vass@Spear:~/filebenchqa/auto-test/filebench-1.4.9$ 

Reported by: vass-vass

**Comment by sectorsize512** [comment]
"usage" command is no longer supported. Closing the ticket.
