### ISSUE TITLE
Set variables from the command line

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#32]
That would be nice to be able to set variable values through the command line. Something like that:

filbench -f varmail.f -s dir=/tmp -s iosize=1m

Reported by: vass-vass

**Comment by sectorsize512** [comment]
From one perspective, this is a great idea and will make the life easier. It's deficiency, however, is that the workload file becomes not self-sufficient. I.e., to share workloads, one needs to share not only the workload files, but also the parameters passed via command line. We need to think more about how to carefully implement this feature.

**Comment by sectorsize512** [comment]
I am closing this issue for now - see my previous comment. We can start the discussion again later, if needed.
