### ISSUE TITLE
Filebench crashes when using directio

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#39]
When using directio in a filebench script, e.g. flowop read name=readfile,filesetname=bigfile1,random,iosize=256k,directio, Filebench crashes with this message:

\*\*\* glibc detected \*\*\* filereader: free\(\): invalid next size \(normal\): 0x00007ff
fe8a008d0 \*\*\*
======= Backtrace: =========
/lib64/libc.so.6\[0x3a0ee76d63\]
/lib64/libc.so.6\(fclose+0x155\)\[0x3a0ee65da5\]
filereader\[0x408d97\]
filereader\[0x40cc22\]
filereader\[0x409033\]
/lib64/libpthread.so.0\[0x3a0f206ccb\]
/lib64/libc.so.6\(clone+0x6d\)\[0x3a0eee0c2d\]

Filebench was runing on Fedora 14, 2.6.35 kernel \(running on a virtual machine on ESX server 4.1\). When I tried the same script on RHEL, 2.6.34.1 kernel \(non-VM setup\), Filebench ran successfully. 

Filebench version 1.4.8

Reported by: *anonymous

**Comment by sectorsize512** [comment]
Fixed with commit d82661c
