### ISSUE TITLE
poor sequential fb perf

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#47]
Have you ever tried comparing the performance of fb vs. iozone or dd?

We aren't too sure about random workloads right now, but for both seq read and write, performance is at least 30% below iozone, and even 70% is some cases when the iosize is very small.  Do you have any insights in this manner, as at this point we cannot use fb until this is resolved.

Here is our sequential write .f file, is there a problem with it?

\#define file name=bigfile1,path=/mnt/boar7,size=1024m,prealloc,reuse,cached=false
define file name=bigfile1,path=/gpfs/gpfsA,size=1024m,prealloc,reuse,cached=false

define process name=filewriter,instances=1
\{
thread name=filewriterthread,memsize=10m,instances=1
\{
flowop write name=writefile,filesetname=bigfile1,iosize=4k,iters=262144
flowop fsync name=fsync
flowop finishonbytes name=finish,value=1
\}
\}

create file
run 6000

Reported by: vass-vass

**Comment by sectorsize512** [comment]
Same as #46. Fixed with 7f635f. Closing the issue, plz, reopen, if it turns out it is still not performing good enough.
