### ISSUE TITLE
filbenchqa: problems with fbmonitor on OpenSolaris

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#52]
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\# starting filebench webserver \(1\)
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
/fbsource/vm\_scripts/fbmonitor.sh: fork: Resource temporarily unavailable
/fbsource/vm\_scripts/fbmonitor.sh: line 38: \[: 1: unary operator expected
/fbsource/vm\_scripts/fbmonitor.sh: fork: Resource temporarily unavailable
Filebench Version 1.4.9
....

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\# starting filebench webserver \(2\)
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
/fbsource/vm\_scripts/fbmonitor.sh: fork: Resource temporarily unavailable
Filebench Version 1.4.9
...

Reported by: vass-vass

**Comment by sectorsize512** [comment]
This one on old filebenchqa, which is not maintained or used anymore. Closing the issue.
