### ISSUE TITLE
Does not build on 64-bit ARM (Aarch64)

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#65]
Filebench will not build for 64-bit ARM (Aarch64).  Attached is a patch that will allow filebench to build.  I tested this using the Aarch64 simulator, since hardware is not yet available.

Please accept this patch to add Aarch64 build support to filebench.
[filebench-aarch64.patch.txt](https://github.com/filebench/filebench/files/351197/filebench-aarch64.patch.txt)

Reported by: *anonymous

**Comment by sectorsize512** [comment]
This issue is supposedly fixed with fe57cd.
