### ISSUE TITLE
Error in `seqread': free(): invalid next size (normal): 0x00007fffd8a008d0

### ISSUE THREAD

**Issue by gamvrosi** [filebench/filebench#67]
Whenever I run any of the *direct workloads, fivestreamreaddirect.f, fivestreamwritedirect.f, singlestreamreaddirect.f, singlestreamwritedirect.f, they all fail with "*** Error in `seqread': free(): invalid next size (normal): 0x00007fffd8a008d0 ***". So far of all the workloads I've tried these are the only workloads which fault.

OpenSUSE 12.3 x86_64 (vmware vm)
Kernel 3.7.10-1.16-default
- filebench-1.4.9.1
(rpm's available at http://download.opensuse.org/repositories/home:/deadpoint/)

Filebench Version 1.4.9.1
31568: 0.000: Allocated 170MB of shared memory
filebench> load fivestreamreaddirect  
31568: 7.382: Five Stream Direct Read Version 3.0 personality successfully loaded
31568: 7.382: Usage: set $dir=<dir>
31568: 7.383:        set $filesize=<size>    defaults to 1073741824
31568: 7.383:        set $nthreads=<value>   defaults to 1
31568: 7.383:        set $iosize=<value> defaults to 1048576
31568: 7.383:        run runtime (e.g. run 60)
filebench> set $dir=/srv/testing/filebench
filebench> run 60
31568: 12.635: Creating/pre-allocating files and filesets
31568: 12.635: File largefile5: 1024.000MB
31568: 12.640: Removed any existing file largefile5 in 1 seconds
31568: 12.641: making tree for filset /srv/testing/filebench/largefile5
31568: 14.224: Creating file largefile5...
31568: 15.456: Preallocated 1 of 1 of file largefile5 in 2 seconds
31568: 15.456: File largefile4: 1024.000MB
31568: 15.480: Removed any existing file largefile4 in 1 seconds
31568: 15.480: making tree for filset /srv/testing/filebench/largefile4
31568: 16.970: Creating file largefile4...
31568: 18.728: Preallocated 1 of 1 of file largefile4 in 2 seconds
31568: 18.731: File largefile3: 1024.000MB
31568: 18.740: Removed any existing file largefile3 in 1 seconds
31568: 18.740: making tree for filset /srv/testing/filebench/largefile3
31568: 19.934: Creating file largefile3...
31568: 21.707: Preallocated 1 of 1 of file largefile3 in 2 seconds
31568: 21.712: File largefile2: 1024.000MB
31568: 21.730: Removed any existing file largefile2 in 1 seconds
31568: 21.730: making tree for filset /srv/testing/filebench/largefile2
31568: 21.730: Creating file largefile2...
31568: 23.447: Preallocated 1 of 1 of file largefile2 in 2 seconds
31568: 23.447: File largefile1: 1024.000MB
31568: 23.515: Removed any existing file largefile1 in 1 seconds
31568: 23.516: making tree for filset /srv/testing/filebench/largefile1
31568: 23.516: Creating file largefile1...
31568: 25.236: Preallocated 1 of 1 of file largefile1 in 2 seconds
31568: 25.236: waiting for fileset pre-allocation to finish
31575: 25.242: Starting 1 seqread instances
31576: 25.283: Starting 1 seqread5 threads
31576: 25.284: Starting 1 seqread4 threads
31576: 25.284: Starting 1 seqread3 threads
31576: 25.284: Starting 1 seqread2 threads
31576: 25.284: Starting 1 seqread1 threads
31568: 26.290: Running...
*** Error in `seqread': free(): invalid next size (normal): 0x00007fffd8a008d0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7abf6)[0x7ffff7386bf6]
/lib64/libc.so.6(+0x7b973)[0x7ffff7387973]
/lib64/libc.so.6(fclose+0x14d)[0x7ffff737724d]
seqread[0x409b3f]
seqread[0x40da52]
seqread[0x409de3]
/lib64/libpthread.so.0(+0x7e0f)[0x7ffff7bc6e0f]
/lib64/libc.so.6(clone+0x6d)[0x7ffff73f47dd]
*** Error in `seqread': free(): invalid next size (normal): 0x00007fffdca008d0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7abf6)[0x7ffff7386bf6]
/lib64/libc.so.6(+0x7b973)[0x7ffff7387973]
======= Memory map: ========
00400000-00431000 r-xp 00000000 08:06 2440                               /usr/bin/filebench
00630000-00631000 r--p 00030000 08:06 2440                               /usr/bin/filebench
00631000-00632000 rw-p 00031000 08:06 2440                               /usr/bin/filebench
00632000-00654000 rw-p 00000000 00:00 0                                  [heap]
7fffd4000000-7fffd4a21000 rw-p 00000000 00:00 0 
7fffd4a21000-7fffd8000000 ---p 00000000 00:00 0 
7fffd8000000-7fffd8a21000 rw-p 00000000 00:00 0 
7fffd8a21000-7fffdc000000 ---p 00000000 00:00 0 
7fffdc000000-7fffdca21000 rw-p 00000000 00:00 0 
7fffdca21000-7fffe0000000 ---p 00000000 00:00 0 
7fffe0000000-7fffe0a21000 rw-p 00000000 00:00 0 
7fffe0a21000-7fffe4000000 ---p 00000000 00:00 0 
7fffe4000000-7fffe4a21000 rw-p 00000000 00:00 0 
7fffe4a21000-7fffe8000000 ---p 00000000 00:00 0 
7fffe9f7d000-7fffe9f92000 r-xp 00000000 08:05 147                        /lib64/libgcc_s.so.1
7fffe9f92000-7fffea191000 ---p 00015000 08:05 147                        /lib64/libg/lib64/libc.so.6(fclose+0x14d)[0x7ffff737724d]
cc_s.so.1
7fffea191000-7fffea192000 r--p 00014000 08:05 147                        /lib64/libgcc_s.so.1
7fffea192000-7fffea193000 rw-p 00015000 08:05 147                        /lib64/libgcc_s.so.1
7fffea193000-7fffea194000 ---p 00000000 00:00 0 
7fffea194000-7fffea994000 rw-p 00000000 00:00 0                          [stack:31581]
7fffea994000-7fffea995000 ---p 00000000 00:00 0 
7fffea995000-7fffeb195000 rw-p 00000000 00:00 0                          [stack:31580]
7fffeb195000-7fffeb196000 ---p 00000000 00:00 0 
7fffeb196000-7fffeb996000 rw-p 00000000 00:00 0                          [stack:31579]
7fffeb996000-7fffeb997000 ---p 00000000 00:00 0 
7fffeb997000-7fffec197000 rw-p 00000000 00:00 0                          [stack:31578]
7fffec197000-7fffec198000 ---p 00000000 00:00 0 
7fffec198000-7fffec998000 rw-p 00000000 00:00 0                          [stack:31577]
7fffec998000-7ffff730c000 rw-s 00000000 08:05 2057                       /tmp/filebench-shm-xe9Gra
7ffff730c000-7ffff74af000 r-xp 00000000 08:05 254                        /lib64/libc-2.17.so
7ffff74af000-7ffff76af000 ---p 001a3000 08:05 254                        /lib64/libc-2.17.so
7ffff76af000-7ffff76b3000 r--p 001a3000 08:05 254                        /lib64/libc-2.17.so
7ffff76b3000-7ffff76b5000 rw-p 001a7000 08:05 254                        /lib64/libc-2.17.so
7ffff76b5000-7ffff76b9000 rw-p 00000000 00:00 0 
7ffff76b9000-7ffff76c0000 r-xp 00000000 08:05 5117                       /lib64/librt-2.17.so
7ffff76c0000-7ffff78bf000 ---p 00007000 08:05 5117                       /lib64/librt-2.17.so
7ffff78bf000-7ffff78c0000 r--p 00006000 08:05 5117                       /lib64/librt-2.17.so
7ffff78c0000-7ffff78c1000 rw-p 00007000 08:05 5117                       /lib64/librt-2.17.so
7ffff78c1000-7ffff79be000 r-xp 00000000 08:05 1848                       /lib64/libm-2.17.so
7ffff79be000-7ffff7bbd000 ---p 000fd000 08:05 1848                       /lib64/libm-2.17.so
7ffff7bbd000-7ffff7bbe000 r--p 000fc000 08:05 1848                       /lib64/libm-2.1seqread[0x409b3f]
7.so
7ffff7bbe000-7ffff7bbf000 rw-p 000fd000 08:05 1848                       /lib64/libm-2.17.so
7ffff7bbf000-7ffff7bd6000 r-xp 00000000 08:05 738                        /lib64/libpthread-2.17.so
7ffff7bd6000-7ffff7dd5000 ---p 00017000 08:05 738                        /lib64/libpthread-2.17.so
7ffff7dd5000-7ffff7dd6000 r--p 00016000 08:05 738                        /lib64/libpthread-2.17.so
7ffff7dd6000-7ffff7dd7000 rw-p 00017000 08:05 738                        /lib64/libpthread-2.17.so
7ffff7dd7000-7ffff7ddb000 rw-p 00000000 00:00 0 
7ffff7ddb000-7ffff7dfc000 r-xp 00000000 08:05 1478                       /lib64/ld-2.17.so
7ffff7fdd000-7ffff7fe1000 rw-p 00000000 00:00 0 
7ffff7ff7000-7ffff7ff8000 rw-p 00000000 00:00 0 
7ffff7ff9000-7ffff7ffb000 rw-p 00000000 00:00 0 
7ffff7ffb000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00021000 08:05 1478                       /lib64/ld-2.17.so
7ffff7ffd000-7ffff7ffe000 rw-p 00022000 08:05 1478                      seqread[0x40da52]
seqread[0x409de3]
/lib64/libpthread.so.0(+0x7e0f)[0x7ffff7bc6e0f]
/lib64/libc.so.6(clone+0x6d)[0x7ffff73f47dd]
 /lib64/ld-2.17.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0 
7ffffffbd000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
31575: 26.329: Unexpected Process termination Code 2, Errno 0 on line 69
31568: 27.291: Run took 1 seconds...
31568: 27.291: NO VALID RESULTS! Filebench run terminated prematurely on line 69
31568: 27.291: Shutting down processes

Reported by: *anonymous

**Comment by sectorsize512** [comment]
Duplicated of #39. Fixed.
