### ISSUE TITLE
Interactive mode not working in 1.5.0-alpha2

### ISSUE THREAD

**Issue by Rondom** [filebench/filebench#79]
In Filebench 1.4.9.1 I would get an interactive prompt when running without parameters.

    $ filebench-1.4.9.1
    Filebench Version 1.4.9.1
    filebench> quit

In 1.5-alpha2 I get a message that I supplied wrong parameters.
    
    $ filebench-1.5-alpha2
    Wrong usage!
    Usage: filebench {-f <wmlscript> | -h | -c [cvartype]}
    Filebench interprets WML script and generates appropriate workload.
    Version 1.5-alpha1
    Visit http://filebench.sourceforge.net/ for WML definition and tutorials.
    Options:
       -f <wmlscript> generate workload from the specified file
       -h             display this help message
       -c             display supported cvar types
       -c [cvartype]  display options of the specific cvar type

**Comment by sectorsize512** [comment]
We decided to remove interactive support in Filebench. Practice showed that is is highly error-prone for system and reliable benchmarking - both from the user perspective and the internal logic. I won't go in details here, but here is the description of the new recommended work flows:

https://github.com/filebench/filebench/wiki#quick-start-guide

**Comment by Rondom** [comment]
Thanks! That was quick.
Maybe add it to the release notes (this is where I looked before filing this issue).

As an extra we could also print out a hint when one runs filebench without parameters.

**Comment by sectorsize512** [comment]
Yeah, I thought along the same lines after reading your issue report :) @gamvrosi, could you add this information to the release notes and a hint message to FB output when you release alpha3 (which will also contain ./configure and such)? Thanks.

**Comment by gamvrosi** [comment]
Resolved in #80, and included in the 1.5-alpha3 release which is now available both here and on SourceForge. Thanks for the pointer, @Rondom.
