### ISSUE TITLE
Special Characters in file bench scripts

### ISSUE THREAD

**Issue by Bvangoor** [filebench/filebench#86]
In order to have better stable performance results, I'm trying to format the underlying EXT4 filesystem for every workload. For that I'm passing the following mkfs command in file bench script:
**system "mkfs.ext4 -F -E  lazy_itable_init=0,lazy_journal_init=0 -O ^uninit_bg /dev/sdb"**

But if you observe the above command, In order to disable the "uninit_bg" we need to pass a "caret(^)" before it. But filebench is not able to recognize it and shows the following error :
**0.048: Illegal character at '^' around line 23**

**Comment by sectorsize512** [comment]
Hey, Bharath, can you see if this fix work for you:

https://github.com/sectorsize512/filebench/tree/issue86test

**Comment by Bvangoor** [comment]
No Vasily. Still it throws this warning :
[root@gr4 kernel-statistics]# filebench -f /home/bvangoor/fuse-playground/workloads/writeback-cache-fuse/seq-write.f
Filebench Version 1.5-alpha3
0.000: Allocated 173MB of shared memory
0.002: Populating and pre-allocating filesets
0.002: bigfileset populated: 1 files, avg. dir. width = 100, avg. dir. depth = 0.0, 0 leafdirs, 0.001MB total size
0.002: Removing bigfileset tree (if exists)
0.005: Pre-allocating directories in bigfileset tree
0.005: Pre-allocating files in bigfileset tree
0.005: Waiting for pre-allocation to finish (in case of a parallel pre-allocation)
0.005: Population and pre-allocation of filesets completed
**0.031: Illegal character at '^' around line 22**
where my file bench script is :
create files
system "mkdir -p /tmp/bigfileset/00000001/"
system "umount /home/bvangoor/EXT4_FS/"
**system "mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0 -O ^uninit_bg /dev/sdb > /dev/null"**
system "mount -t ext4 /dev/sdb /home/bvangoor/EXT4_FS/"
system "sync"
system "echo 3 > /proc/sys/vm/drop_caches"
system "/home/bvangoor/fuse-playground/StackFS_LowLevel/StackFS_ll -o max_write=1048576 -o writeback_cache --tracing --attrval=1000000 --statsdir=/tmp/ -r /home/bvangoor/EXT4_FS/ /tmp/bigfileset/00000001/ > /dev/null &"

**Comment by sectorsize512** [comment]
Can you confirm that you've recompiled the code and installed the newly compiled Filebench binary? Do you use issu86fix branch? It's just that it seems to work on my installation...

**Comment by Bvangoor** [comment]
I did a ``git pull'' and then recompiled and installed.

**Comment by sectorsize512** [comment]
but then you pulled from the master branch of the different repo. You need to clone my repo (sectorsize512), then switch to issue86fix, then recompile and reinstall.

**Comment by sectorsize512** [comment]
basically verify that commit 441538425f38907d8abbd1cb1bfc4a029b4535bf is there

**Comment by Bvangoor** [comment]
Sorry for the confusion, Yes I tested the fix it is now working.

Thanks Vasily for the fix.

**Comment by sectorsize512** [comment]
thanks for reporting the issue and testing the fix out :)

**Comment by sectorsize512** [comment]
Fixed with 4415384
