### ISSUE TITLE
File bench terminates as soon as the completion of one thread work even though there are some other threads still unfinished, even after specifying "finishoncount" and "quit alldone"

### ISSUE THREAD

**Issue by Bvangoor** [filebench/filebench#88]
In case of one process, two threads writing to two different files. After the run I verified the size of files :
[root@gr1 No-fuse]# ls -lrt /home/bvangoor/EXT4_FS/bigfileset/00000001/
total 4100960
-rw-r--r--. 1 root root **2147483648** Aug  3 20:41 00000001
-rw-r--r--. 1 root root **2051891200** Aug  3 20:42 00000002
[root@gr1 No-fuse]# sync
[root@gr1 No-fuse]# ls -lrt /home/bvangoor/EXT4_FS/bigfileset/00000001/
total 4100960
-rw-r--r--. 1 root root **2147483648** Aug  3 20:41 00000001
-rw-r--r--. 1 root root **2051891200** Aug  3 20:42 00000002

It is because as soon as one of the thread finishes the job, the file bench comes out ? But I've given "**set mode quit alldone**"

My filebench script is :

set mode quit alldone
define process name=filesequentialwrite, instances=1
{
        thread name=filewriter, memsize=4k, instances=1        
        {
                flowop createfile name=create1, filesetname=bigfileset, fd=1
                flowop write name=write-file1, filesetname=bigfileset, iosize=4k, iters=524288, fd=1
                flowop closefile name=close1, fd=1
                flowop finishoncount name=finish, value=1
        }

        thread name=filewriter, memsize=4k, instances=1
        {
                flowop createfile name=create2, filesetname=bigfileset, fd=2
                flowop write name=write-file2, filesetname=bigfileset, iosize=4k, iters=524288, fd=2
                flowop closefile name=close2, fd=2
                flowop finishoncount name=finish, value=1
        }

}

**Comment by sectorsize512** [comment]
Hey, Bharath, could you see if commit 72646db fixes the issues?

**Comment by Bvangoor** [comment]
Thanks Vasily. It's working now I've verified.

**Comment by sectorsize512** [comment]
Fixed with 0d255ef2fa87d2aec74d7792ac83c7ca39a5f07d.
