### ISSUE TITLE
configure shell missing

### ISSUE THREAD

**Issue by nikokio** [filebench/filebench#93]
Hello.

When downloading from https://github.com/filebench/filebench/releases, whatever the version downloaded, the configure script is missing, therefore it is not possible to compile following the instructions in the INSTALL file...

Thanks

**Comment by gamvrosi** [comment]
Hi,

Try downloading the latest pre-release ([1.5-alpha3](https://github.com/filebench/filebench/releases/tag/1.5-alpha3)). This one contains the appropriate files for compiling without running autotools.

Hope this helps,
George
