### ISSUE TITLE
How to print thread-ids and their jobs in Filebench?

### ISSUE THREAD

**Issue by husna2001** [filebench/filebench#94]
Hi,
Presently I am passing Workload Model Language(WML) file mywebserver.f for the mywebserver application which prints what are the files accessed and flowops on them. I need to print all created thread-ids and the filenames as well as flowops they perform. How to get this information?

**Comment by gamvrosi** [comment]
Are you looking to print thread IDs and filenames for every flowop that is executed? To the best of my knowledge, there is no way to do that through the WML currently (@sectorsize512 can correct me if I'm wrong).

To do this, you could instrument the filebench code and have it print this information out. And if you're willing to go one step further, you could expose this through the WML by adding a `debug` or `trace` directive to the `flowop` command.

**Comment by husna2001** [comment]
Yes, I am looking to print those information out. I can see all these information are in the threadflow.c file within filebench_log(). But I don't have any idea how to print those out. Now, I am using the following command :
filebench -f mywebserver.f

What should I do to print something like "Checking pid %d thread %s-%d" (line 310, threadflow.c)? Should I just use printf and build the filebench to print out those thread related information?

**Comment by gamvrosi** [comment]
I suggest using `filebench_log()` (see `misc.c`). The first argument is the logging level, and filebench by default prints only messages that fall under level `LOG_INFO`. I suggest using either the `LOG_DEBUG_SCRIPT` or the `LOG_VERBOSE` level for the information you want to print (see all the available levels at `misc.h`). You can set the max level that should be printed to stdout through `filebench_shm->shm_debug_level`.

Hope this helps!

**Comment by sectorsize512** [comment]
Add debug command to the top of your .f file with appropriate debug level. Here is the link to documentation:

https://github.com/filebench/filebench/wiki/Workload-model-language#debug


HTH,Vasily
