### ISSUE TITLE
Understanding reported filebench latencies

### ISSUE THREAD

**Issue by ashokkumaralluri** [filebench/filebench#96]
Hi Team,

I am trying to understand the latencies reported by filebench tool. How are they calculated?

**Report1:**
Using single instance and 16 threads, testing create and closefile ops
```
312.038: Run took 300 seconds...
312.038: Per-Operation Breakdown
closefile1           13804ops       46ops/s   0.0mb/s      0.0ms/op [0.00ms -  0.38ms]
createfile1          13804ops       46ops/s   0.0mb/s    347.6ms/op [8.74ms - 5261.88ms]
312.038: IO Summary: 27608 ops 92.019 ops/s 0/0 rd/wr   0.0mb/s   0.0ms/op
```
**Report2:**
Using 20 instances and 20 threads, testing create and closefile ops
```
281.546: Run took 266 seconds...
281.551: Per-Operation Breakdown
closefile1           49601ops      186ops/s   0.0mb/s      0.0ms/op [0.00ms -  6.00ms]
createfile1          49675ops      187ops/s   0.0mb/s   2129.8ms/op [9.47ms - 12856.15ms]
281.551: IO Summary: 99276 ops 373.188 ops/s 0/0 rd/wr   0.0mb/s   0.0ms/op
```

I am trying to understand the reason why  the create latencies are so deviated from others when I change instances and threads.  Underlying storage layer reports same 50ms-100ms mean latencies always , where as filebench deviates a lot. I am quite sure that no op took 12856ms for sure but max range of create file op report says so.

@gamvrosi 

Thanks,
Ashok

**Comment by sectorsize512** [comment]
Hi Ashok,

My understanding is that Filebench maintains average, minimum, and maximum latencies among all flowop executions, no matter in which process/thread the flowop was executed.

So,  the line 

> createfile1          13804ops       46ops/s   0.0mb/s    347.6ms/op [8.74ms - 5261.88ms]

means that across all 16 threads the average latency of createfile1 flowop was ~348ms, minimum latency was about ~8ms and maximum over 5 seconds.

I'm not sure what do you mean by "instances" (single vs. 20). But generally the more threads you run, the more load you have on the system, and therefore the latencies grow. If you look at conventional throughput vs. latency graph (e.g., https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiT_PXY89DQAhUf0IMKHS8fBLQQjRwIBw&url=http%3A%2F%2Fwww.futurechips.org%2Fchip-design-for-all%2Flittles-law.html&psig=AFQjCNE4bLNaXRp_T_jV37I3gcl_xwGXVQ&ust=1480609861504525) you can see how the latency grows as you have higher throughput (which is achieved by more threads/clients submitting the request).

HTH,
Vasily

**Comment by ashokkumaralluri** [comment]
Thanks Vasily, nice reference!! Now I am able to get it why latencies are high.

**I'm not sure what do you mean by "instances"**   ==>> Sorry I missed to mention that "process" instances.

**Comment by sectorsize512** [comment]
Glad I was able to help. Closing the issue, but feel free to reopen it or open a new one if you have any questions.
