### ISSUE TITLE
Why there is no i/o performance when i use filebench to test flowop read operation?

### ISSUE THREAD

**Issue by i4oolish** [filebench/filebench#99]
We have a NVMe SSD, mounted on /nvme, the workload.f edit as fllows:

-------
set $dir=/nvme/read
set $iosize=4k
set $filesize=50k
set $nfiles=1000000
set $width=20
set $memsize=1m
set $nthreads=256

define fileset name=datafiles,path=$dir,size=$filesize,entries=$nfiles,dirwidth=$width,prealloc=100,reuse
define process name=readfiles,instances=1
{
  thread name=readthd,memsize=$memsize,instances=$nthreads
  {
    flowop read name=readfile,filesetname=datafiles,iosize=$iosize,random,opennext
  }
}

system "echo 3 > /proc/sys/vm/drop_caches"
run 60

--------

I use nmon to monitor the I/O on NVMe SSD, but don't see any read throughput, is there any question?

**Comment by sectorsize512** [comment]
Can you paste Filebench output here?

Thanks,
Vasily

**Comment by i4oolish** [comment]
Our machine environment is:  Linux4.4.24 , 120cpu cores, 16G memory.
And I changed the source code: modify the **FILEBENCH_NFILESETENTRIES   to   (1024 * 1024 * 64).** 
The output is show as below:

-----------------

root@R920:/home/shz/filebench/workloads# filebench -f read.f
Filebench Version 1.5-alpha3
0.000: Allocated 9497MB of shared memory
0.919: Populating and pre-allocating filesets
2.956: datafiles populated: 1000000 files, avg. dir. width = 20, avg. dir. depth = 4.6, 0 leafdirs, 48828.125MB total size
2.956: Removing datafiles tree (if exists)
4.526: Pre-allocating directories in datafiles tree
5.945: Pre-allocating files in datafiles tree
118.252: Waiting for pre-allocation to finish (in case of a parallel pre-allocation)
118.252: Population and pre-allocation of filesets completed
118.293: Starting 1 readfiles instances
119.478: Running...
179.484: Run took 60 seconds...
179.485: Per-Operation Breakdown
readfile             48373316ops   806142ops/s 3146.9mb/s      0.0ms/op [0.00ms - 308.24ms]
179.485: IO Summary: 48373316 ops 806142.219 ops/s 806142/0 rd/wr 3146.9mb/s   0.0ms/op
179.485: Shutting down processes

-----------------

I have suspect maybe the reason is filebench only read a small file set, so i add code **fprintf(stderr, "pread, fd = %d\n", fd->fd_num);** in fb_lfs_pread, and the log shows that the fd range is [10 ,9999], and i parse a small piece output below: 

--------------------

pread, fd = 10
pread, fd = 7
pread, fd = 6
pread, fd = 9
pread, fd = 8
pread, fd = 11
pread, fd = 12
pread, fd = 14
pread, fd = 13
pread, fd = 15
pread, fd = 16
pread, fd = 18
pread, fd = 20
pread, fd = 17
pread, fd = 19
pread, fd = 21
pread, fd = 22
pread, fd = 27
pread, fd = 26
pread, fd = 23
pread, fd = 29
pread, fd = 24
pread, fd = 28
pread, fd = 34
pread, fd = 25
pread, fd = 41
pread, fd = 31
pread, fd = 30
pread, fd = 36
pread, fd = 45
pread, fd = 49
pread, fd = 50
pread, fd = 52
pread, fd = 51
pread, fd = 40
pread, fd = 42

......

pread, fd = 19457
pread, fd = 15932
pread, fd = 14383
pread, fd = 2787
pread, fd = 9997
pread, fd = 27737
pread, fd = 15952
pread, fd = 15414
pread, fd = 2678
pread, fd = 16181
pread, fd = 29073
pread, fd = 15156
pread, fd = 25202
pread, fd = 23056
pread, fd = 26654
pread, fd = 29504
pread, fd = 3908
pread, fd = 9472
pread, fd = 31921
pread, fd = 13664
pread, fd = 19426
pread, fd = 23331
pread, fd = 2730
pread, fd = 20845
pread, fd = 29114
pread, fd = 28982
pread, fd = 32358
pread, fd = 26065
pread, fd = 27218
pread, fd = 16060
pread, fd = 24391
pread, fd = 825
pread, fd = 4315
pread, fd = 26524
pread, fd = 3580

----------------------

Thanks,
Haizhu Shao

**Comment by i4oolish** [comment]
Maybe i have know the reason. The file size in my workload is 50k, and **the fd filebench can opened is only 32768**, so filebench will only read **32768 * 50k = 1.5625GB data into filesystem cache**. The result is although we run 60 seconds, the filebench only read data in filesystem cache, so the nmon cannot monitor the i/o (only read these 1.5625GB data in the begin.)

Is my analysis is right? If right, can you tell me, where can i modify the **open fd limit**.

**Comment by i4oolish** [comment]
I know why i see the fd can be opened 32768. **In file threadflow.h, it define THREADFLOW_MAXFD 128**. 

I changed THREADFLOW_MAXFD to 8000, but the filebench run error, the errmsg is 

> Failed to open file 358, /nvme/read/datafiles/00000001/00000359, with status 38: Too many open files

**Comment by sectorsize512** [comment]
Hi Haizhu,

Nice analysis. Even thought the set of file descriptors is limited they can still address different files. The problem here is that your workload does not close any files, and therefore descriptors remain open and refer to same files. (BTW, real applications usually also limit the number of open files, and Linux, as you can see in your last output, also limits using, e.g., ulimit mechanism).

What I suggest is too modify your workload to open and close files explicitly, something along these lines:

```
flowop open name=openfile,filesetname=datafiles,fd=1
flowop read name=readfile,filesetname=datafiles,iosize=$iosize,random,fd=1
flowop close name=closefile,filesetname=datafiles,fd=1
```

HTH,
Vasily

**Comment by i4oolish** [comment]
Thank you very much for your suggestion, it's very userful for me.
